### ISSUE TITLE
The "road" id in map matching results

### ISSUE THREAD

**Issue by hujilin1229** [boathit/deepgtt#3]
Hi Xiucheng,

Thanks for sharing your work. Recently, I tried to rerun your code and encounter one problem. After I built the road network of Harbin, I found the table "bfmap_ways" has a total of 8497 rows, which means the "gid" with a maximum value of 8497. However, some of map matching results, for example, 
 "Dict{String,Any}("heading" => "forward","frac" => 0.7377781424331177,"route" => "LINESTRING (126.62966262426313 45.691261524537865, 126.62976270000001 45.6908025, 126.6300707 45.6908319, 126.62975139256004 45.692285544498645)","road" => 15054)"

Here the "road" id should be corresponding to gid in "bfmap_ways", but it is of course larger than 8497. So I would like to ask how do you handle this problem? 

Kind Regards,
Jilin

**Comment by boathit** [comment]
Hi Jilin, the code of using the obtained road id in in [this](https://github.com/boathit/deepgtt/blob/master/harbin/python/model.py#L96) line, where the dict is constructed in [this](https://github.com/boathit/deepgtt/blob/master/harbin/python/db_utils.py) file. The code does not handle the case where road id is out of the maximum of gid, but it runs well. It seems the map matching results obtained using [my code](https://github.com/boathit/deepgtt/blob/master/harbin/julia/mapmatch.jl) all falls into proper range, I guess it may because I have preprocessed raw trajectories [here](https://github.com/boathit/deepgtt/blob/master/harbin/julia/mapmatch.jl#L38).

**Comment by hujilin1229** [comment]
> Hi Jilin, the code of using the obtained road id in in [this](https://github.com/boathit/deepgtt/blob/master/harbin/python/model.py#L96) line, where the dict is constructed in [this](https://github.com/boathit/deepgtt/blob/master/harbin/python/db_utils.py) file. The code does not handle the case where road id is out of the maximum of gid, but it runs well. It seems the map matching results obtained using [my code](https://github.com/boathit/deepgtt/blob/master/harbin/julia/mapmatch.jl) all falls into proper range, I guess it may because I have preprocessed raw trajectories [here](https://github.com/boathit/deepgtt/blob/master/harbin/julia/mapmatch.jl#L38).

Hi Xiucheng, thanks. I'll go back to check the map matched results.

**Comment by hujilin1229** [comment]
Hi Xiucheng,

Sorry to interrupt again! I'm wondering whether you have checked the map matched results. When I try to visualize the map matched results (*.jld2 file) using your provided "deepgtt-julia.ipynb", I found the resulted gps.txt and road.txt file does not match well. I'm running exactly the command that you provided in ReadMe, so I'm trying to find what can be the reason for this case. Moreover, in "road.txt", there are several roads with id large than 8497. 

Kind Regards,
Jilin

**Comment by hujilin1229** [comment]
> Hi Xiucheng,
> 
> Sorry to interrupt again! I'm wondering whether you have checked the map matched results. When I try to visualize the map matched results (*.jld2 file) using your provided "deepgtt-julia.ipynb", I found the resulted gps.txt and road.txt file does not match well. I'm running exactly the command that you provided in ReadMe, so I'm trying to find what can be the reason for this case. Moreover, in "road.txt", there are several roads with id large than 8497.
> 
> Kind Regards,
> Jilin

I think I found the reason for this problem due to the map matching server. So I'll close this problem.
